require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

Style/Documentation:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/DescribeClass:
  Enabled: false
