version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"

    environment:
      RAILS_LOG_TO_STDOUT: true
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_PASSWD: postgres

    depends_on:
      - db
