---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/performances":
    post:
      summary: Creates a performance
      tags:
      - Performances
      parameters: []
      responses:
        '201':
          description: performance created
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  start_date:
                    type: string
                    format: date
                  end_date:
                    type: string
                    format: date
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                required:
                - title
                - start_date
                - end_date
                - created_at
                - updated_at
        '422':
          description: performance dates overlap
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  nullable: false
                start_date:
                  type: string
                  nullable: false
                  format: date
                  example: '2020-01-01'
                end_date:
                  type: string
                  nullable: false
                  format: date
                  example: '2020-01-01'
              required:
              - title
              - start_date
              - end_date
    get:
      summary: Retrieves performances
      tags:
      - Performances
      parameters:
      - name: page
        in: query
        description: Page number
        schema:
          type: integer
      - name: per_page
        in: query
        description: Number of items per page
        schema:
          type: integer
      responses:
        '200':
          description: performances found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        title:
                          type: string
                        start_date:
                          type: string
                          format: date
                        end_date:
                          type: string
                          format: date
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                  current_page:
                    type: integer
                  per_page:
                    type: integer
                  total_pages:
                    type: integer
                required:
                - data
                - current_page
                - per_page
                - total_pages
  "/api/v1/performances/{id}":
    delete:
      summary: Removes a performance
      tags:
      - Performances
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: performance deleted
        '404':
          description: performance not found
  "/api/healthcheck/ready":
    get:
      summary: Returns health check ready
      tags:
      - Health
      responses:
        '200':
          description: OK
  "/api/healthcheck/live":
    get:
      summary: Returns health live status
      tags:
      - Health
      responses:
        '200':
          description: OK
servers:
- url: "{schema}{defaultHost}{path}"
  variables:
    defaultHost:
      default: localhost
    schema:
      default: https://
      enum:
      - https://
      - http://
    path:
      default: "/"
      enum:
      - "/"
